/*
 * Copyright 2019-2020 Dgraph Labs, Inc. and Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	dgraphiov1alpha1 "github.com/dgraph-io/dgraph-operator/pkg/apis/dgraph.io/v1alpha1"
	versioned "github.com/dgraph-io/dgraph-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/dgraph-io/dgraph-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/dgraph-io/dgraph-operator/pkg/client/listers/dgraph.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DgraphClusterInformer provides access to a shared informer and lister for
// DgraphClusters.
type DgraphClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DgraphClusterLister
}

type dgraphClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDgraphClusterInformer constructs a new informer for DgraphCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDgraphClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDgraphClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDgraphClusterInformer constructs a new informer for DgraphCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDgraphClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DgraphV1alpha1().DgraphClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DgraphV1alpha1().DgraphClusters(namespace).Watch(options)
			},
		},
		&dgraphiov1alpha1.DgraphCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *dgraphClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDgraphClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dgraphClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dgraphiov1alpha1.DgraphCluster{}, f.defaultInformer)
}

func (f *dgraphClusterInformer) Lister() v1alpha1.DgraphClusterLister {
	return v1alpha1.NewDgraphClusterLister(f.Informer().GetIndexer())
}
