/*
 * Copyright 2019-2020 Dgraph Labs, Inc. and Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/dgraph-io/dgraph-operator/pkg/apis/dgraph.io/v1alpha1"
	scheme "github.com/dgraph-io/dgraph-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DgraphClustersGetter has a method to return a DgraphClusterInterface.
// A group's client should implement this interface.
type DgraphClustersGetter interface {
	DgraphClusters(namespace string) DgraphClusterInterface
}

// DgraphClusterInterface has methods to work with DgraphCluster resources.
type DgraphClusterInterface interface {
	Create(*v1alpha1.DgraphCluster) (*v1alpha1.DgraphCluster, error)
	Update(*v1alpha1.DgraphCluster) (*v1alpha1.DgraphCluster, error)
	UpdateStatus(*v1alpha1.DgraphCluster) (*v1alpha1.DgraphCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DgraphCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.DgraphClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DgraphCluster, err error)
	DgraphClusterExpansion
}

// dgraphClusters implements DgraphClusterInterface
type dgraphClusters struct {
	client rest.Interface
	ns     string
}

// newDgraphClusters returns a DgraphClusters
func newDgraphClusters(c *DgraphV1alpha1Client, namespace string) *dgraphClusters {
	return &dgraphClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dgraphCluster, and returns the corresponding dgraphCluster object, and an error if there is any.
func (c *dgraphClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.DgraphCluster, err error) {
	result = &v1alpha1.DgraphCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dgraphclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DgraphClusters that match those selectors.
func (c *dgraphClusters) List(opts v1.ListOptions) (result *v1alpha1.DgraphClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DgraphClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dgraphclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dgraphClusters.
func (c *dgraphClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dgraphclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a dgraphCluster and creates it.  Returns the server's representation of the dgraphCluster, and an error, if there is any.
func (c *dgraphClusters) Create(dgraphCluster *v1alpha1.DgraphCluster) (result *v1alpha1.DgraphCluster, err error) {
	result = &v1alpha1.DgraphCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dgraphclusters").
		Body(dgraphCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dgraphCluster and updates it. Returns the server's representation of the dgraphCluster, and an error, if there is any.
func (c *dgraphClusters) Update(dgraphCluster *v1alpha1.DgraphCluster) (result *v1alpha1.DgraphCluster, err error) {
	result = &v1alpha1.DgraphCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dgraphclusters").
		Name(dgraphCluster.Name).
		Body(dgraphCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *dgraphClusters) UpdateStatus(dgraphCluster *v1alpha1.DgraphCluster) (result *v1alpha1.DgraphCluster, err error) {
	result = &v1alpha1.DgraphCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dgraphclusters").
		Name(dgraphCluster.Name).
		SubResource("status").
		Body(dgraphCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the dgraphCluster and deletes it. Returns an error if one occurs.
func (c *dgraphClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dgraphclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dgraphClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dgraphclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dgraphCluster.
func (c *dgraphClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DgraphCluster, err error) {
	result = &v1alpha1.DgraphCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dgraphclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
