/*
 * Copyright 2019-2020 Dgraph Labs, Inc. and Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/dgraph-io/dgraph-operator/pkg/apis/dgraph.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDgraphClusters implements DgraphClusterInterface
type FakeDgraphClusters struct {
	Fake *FakeDgraphV1alpha1
	ns   string
}

var dgraphclustersResource = schema.GroupVersionResource{Group: "dgraph.io", Version: "v1alpha1", Resource: "dgraphclusters"}

var dgraphclustersKind = schema.GroupVersionKind{Group: "dgraph.io", Version: "v1alpha1", Kind: "DgraphCluster"}

// Get takes name of the dgraphCluster, and returns the corresponding dgraphCluster object, and an error if there is any.
func (c *FakeDgraphClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.DgraphCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dgraphclustersResource, c.ns, name), &v1alpha1.DgraphCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DgraphCluster), err
}

// List takes label and field selectors, and returns the list of DgraphClusters that match those selectors.
func (c *FakeDgraphClusters) List(opts v1.ListOptions) (result *v1alpha1.DgraphClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dgraphclustersResource, dgraphclustersKind, c.ns, opts), &v1alpha1.DgraphClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DgraphClusterList{ListMeta: obj.(*v1alpha1.DgraphClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.DgraphClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dgraphClusters.
func (c *FakeDgraphClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dgraphclustersResource, c.ns, opts))

}

// Create takes the representation of a dgraphCluster and creates it.  Returns the server's representation of the dgraphCluster, and an error, if there is any.
func (c *FakeDgraphClusters) Create(dgraphCluster *v1alpha1.DgraphCluster) (result *v1alpha1.DgraphCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dgraphclustersResource, c.ns, dgraphCluster), &v1alpha1.DgraphCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DgraphCluster), err
}

// Update takes the representation of a dgraphCluster and updates it. Returns the server's representation of the dgraphCluster, and an error, if there is any.
func (c *FakeDgraphClusters) Update(dgraphCluster *v1alpha1.DgraphCluster) (result *v1alpha1.DgraphCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dgraphclustersResource, c.ns, dgraphCluster), &v1alpha1.DgraphCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DgraphCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDgraphClusters) UpdateStatus(dgraphCluster *v1alpha1.DgraphCluster) (*v1alpha1.DgraphCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dgraphclustersResource, "status", c.ns, dgraphCluster), &v1alpha1.DgraphCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DgraphCluster), err
}

// Delete takes name of the dgraphCluster and deletes it. Returns an error if one occurs.
func (c *FakeDgraphClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dgraphclustersResource, c.ns, name), &v1alpha1.DgraphCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDgraphClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dgraphclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DgraphClusterList{})
	return err
}

// Patch applies the patch and returns the patched dgraphCluster.
func (c *FakeDgraphClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DgraphCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dgraphclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.DgraphCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DgraphCluster), err
}
