/*
 * Copyright 2019-2020 Dgraph Labs, Inc. and Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/dgraph-io/dgraph-operator/pkg/apis/dgraph.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DgraphClusterLister helps list DgraphClusters.
type DgraphClusterLister interface {
	// List lists all DgraphClusters in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.DgraphCluster, err error)
	// DgraphClusters returns an object that can list and get DgraphClusters.
	DgraphClusters(namespace string) DgraphClusterNamespaceLister
	DgraphClusterListerExpansion
}

// dgraphClusterLister implements the DgraphClusterLister interface.
type dgraphClusterLister struct {
	indexer cache.Indexer
}

// NewDgraphClusterLister returns a new DgraphClusterLister.
func NewDgraphClusterLister(indexer cache.Indexer) DgraphClusterLister {
	return &dgraphClusterLister{indexer: indexer}
}

// List lists all DgraphClusters in the indexer.
func (s *dgraphClusterLister) List(selector labels.Selector) (ret []*v1alpha1.DgraphCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DgraphCluster))
	})
	return ret, err
}

// DgraphClusters returns an object that can list and get DgraphClusters.
func (s *dgraphClusterLister) DgraphClusters(namespace string) DgraphClusterNamespaceLister {
	return dgraphClusterNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// DgraphClusterNamespaceLister helps list and get DgraphClusters.
type DgraphClusterNamespaceLister interface {
	// List lists all DgraphClusters in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.DgraphCluster, err error)
	// Get retrieves the DgraphCluster from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.DgraphCluster, error)
	DgraphClusterNamespaceListerExpansion
}

// dgraphClusterNamespaceLister implements the DgraphClusterNamespaceLister
// interface.
type dgraphClusterNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all DgraphClusters in the indexer for a given namespace.
func (s dgraphClusterNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.DgraphCluster, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DgraphCluster))
	})
	return ret, err
}

// Get retrieves the DgraphCluster from the indexer for a given namespace and name.
func (s dgraphClusterNamespaceLister) Get(name string) (*v1alpha1.DgraphCluster, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("dgraphcluster"), name)
	}
	return obj.(*v1alpha1.DgraphCluster), nil
}
