// +build !ignore_autogenerated

/*
 * Copyright 2019-2020 Dgraph Labs, Inc. and Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlphaClusterSpec) DeepCopyInto(out *AlphaClusterSpec) {
	*out = *in
	in.DgraphComponentSpec.DeepCopyInto(&out.DgraphComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(AlphaConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlphaClusterSpec.
func (in *AlphaClusterSpec) DeepCopy() *AlphaClusterSpec {
	if in == nil {
		return nil
	}
	out := new(AlphaClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlphaClusterStatus) DeepCopyInto(out *AlphaClusterStatus) {
	*out = *in
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(v1.StatefulSetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make(map[string]DgraphComponent, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlphaClusterStatus.
func (in *AlphaClusterStatus) DeepCopy() *AlphaClusterStatus {
	if in == nil {
		return nil
	}
	out := new(AlphaClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlphaConfig) DeepCopyInto(out *AlphaConfig) {
	*out = *in
	out.DgraphConfig = in.DgraphConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlphaConfig.
func (in *AlphaConfig) DeepCopy() *AlphaConfig {
	if in == nil {
		return nil
	}
	out := new(AlphaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphCluster) DeepCopyInto(out *DgraphCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphCluster.
func (in *DgraphCluster) DeepCopy() *DgraphCluster {
	if in == nil {
		return nil
	}
	out := new(DgraphCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DgraphCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphClusterList) DeepCopyInto(out *DgraphClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DgraphCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphClusterList.
func (in *DgraphClusterList) DeepCopy() *DgraphClusterList {
	if in == nil {
		return nil
	}
	out := new(DgraphClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DgraphClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphClusterSpec) DeepCopyInto(out *DgraphClusterSpec) {
	*out = *in
	in.AlphaCluster.DeepCopyInto(&out.AlphaCluster)
	in.ZeroCluster.DeepCopyInto(&out.ZeroCluster)
	in.Ratel.DeepCopyInto(&out.Ratel)
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ResourceRequirements.DeepCopyInto(&out.ResourceRequirements)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphClusterSpec.
func (in *DgraphClusterSpec) DeepCopy() *DgraphClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DgraphClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphClusterStatus) DeepCopyInto(out *DgraphClusterStatus) {
	*out = *in
	in.AlphaCluster.DeepCopyInto(&out.AlphaCluster)
	in.ZeroCluster.DeepCopyInto(&out.ZeroCluster)
	out.Ratel = in.Ratel
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphClusterStatus.
func (in *DgraphClusterStatus) DeepCopy() *DgraphClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DgraphClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphComponent) DeepCopyInto(out *DgraphComponent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphComponent.
func (in *DgraphComponent) DeepCopy() *DgraphComponent {
	if in == nil {
		return nil
	}
	out := new(DgraphComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphComponentSpec) DeepCopyInto(out *DgraphComponentSpec) {
	*out = *in
	in.ResourceRequirements.DeepCopyInto(&out.ResourceRequirements)
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphComponentSpec.
func (in *DgraphComponentSpec) DeepCopy() *DgraphComponentSpec {
	if in == nil {
		return nil
	}
	out := new(DgraphComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DgraphConfig) DeepCopyInto(out *DgraphConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DgraphConfig.
func (in *DgraphConfig) DeepCopy() *DgraphConfig {
	if in == nil {
		return nil
	}
	out := new(DgraphConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatelSpec) DeepCopyInto(out *RatelSpec) {
	*out = *in
	in.DgraphComponentSpec.DeepCopyInto(&out.DgraphComponentSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatelSpec.
func (in *RatelSpec) DeepCopy() *RatelSpec {
	if in == nil {
		return nil
	}
	out := new(RatelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatelStatus) DeepCopyInto(out *RatelStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatelStatus.
func (in *RatelStatus) DeepCopy() *RatelStatus {
	if in == nil {
		return nil
	}
	out := new(RatelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroClusterSpec) DeepCopyInto(out *ZeroClusterSpec) {
	*out = *in
	in.DgraphComponentSpec.DeepCopyInto(&out.DgraphComponentSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ZeroConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroClusterSpec.
func (in *ZeroClusterSpec) DeepCopy() *ZeroClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ZeroClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroClusterStatus) DeepCopyInto(out *ZeroClusterStatus) {
	*out = *in
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(v1.StatefulSetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make(map[string]DgraphComponent, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroClusterStatus.
func (in *ZeroClusterStatus) DeepCopy() *ZeroClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ZeroClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroConfig) DeepCopyInto(out *ZeroConfig) {
	*out = *in
	out.DgraphConfig = in.DgraphConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroConfig.
func (in *ZeroConfig) DeepCopy() *ZeroConfig {
	if in == nil {
		return nil
	}
	out := new(ZeroConfig)
	in.DeepCopyInto(out)
	return out
}
